// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/account/_middleware.ts";
import * as $5 from "./routes/account/create/[page].tsx";
import * as $6 from "./routes/account/create/index.tsx";
import * as $7 from "./routes/api/oauth/token.tsx";
import * as $8 from "./routes/dev/dashboard/_middleware.ts";
import * as $9 from "./routes/dev/dashboard/app/[id]/index.tsx";
import * as $10 from "./routes/dev/dashboard/create-app.tsx";
import * as $11 from "./routes/dev/dashboard/index.tsx";
import * as $12 from "./routes/dev/index.tsx";
import * as $13 from "./routes/dev/login.tsx";
import * as $14 from "./routes/docs/[...slug].tsx";
import * as $15 from "./routes/docs/out.tsx";
import * as $16 from "./routes/gfm.css.ts";
import * as $17 from "./routes/home.tsx";
import * as $18 from "./routes/index.tsx";
import * as $19 from "./routes/login.tsx";
import * as $20 from "./routes/logout.tsx";
import * as $21 from "./routes/oauth2/auth.tsx";
import * as $22 from "./routes/oauth2/forgot-password.tsx";
import * as $23 from "./routes/oauth2/fync/callback.tsx";
import * as $24 from "./routes/oauth2/fync/index.tsx";
import * as $25 from "./routes/oauth2/google/callback.tsx";
import * as $26 from "./routes/oauth2/google/index.tsx";
import * as $27 from "./routes/oauth2/login.tsx";
import * as $28 from "./routes/signup.tsx";
import * as $$0 from "./islands/AccountForm.tsx";
import * as $$1 from "./islands/AppDataEditor.tsx";
import * as $$2 from "./islands/Banner.tsx";
import * as $$3 from "./islands/CopyButton.tsx";
import * as $$4 from "./islands/CopyText.tsx";
import * as $$5 from "./islands/Counter.tsx";
import * as $$6 from "./islands/Input.tsx";
import * as $$7 from "./islands/Login.tsx";
import * as $$8 from "./islands/PersonalForm.tsx";
import * as $$9 from "./islands/ProfileNavButton.tsx";
import * as $$10 from "./islands/SearchButton.tsx";
import * as $$11 from "./islands/UserNavbar.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/account/_middleware.ts": $4,
    "./routes/account/create/[page].tsx": $5,
    "./routes/account/create/index.tsx": $6,
    "./routes/api/oauth/token.tsx": $7,
    "./routes/dev/dashboard/_middleware.ts": $8,
    "./routes/dev/dashboard/app/[id]/index.tsx": $9,
    "./routes/dev/dashboard/create-app.tsx": $10,
    "./routes/dev/dashboard/index.tsx": $11,
    "./routes/dev/index.tsx": $12,
    "./routes/dev/login.tsx": $13,
    "./routes/docs/[...slug].tsx": $14,
    "./routes/docs/out.tsx": $15,
    "./routes/gfm.css.ts": $16,
    "./routes/home.tsx": $17,
    "./routes/index.tsx": $18,
    "./routes/login.tsx": $19,
    "./routes/logout.tsx": $20,
    "./routes/oauth2/auth.tsx": $21,
    "./routes/oauth2/forgot-password.tsx": $22,
    "./routes/oauth2/fync/callback.tsx": $23,
    "./routes/oauth2/fync/index.tsx": $24,
    "./routes/oauth2/google/callback.tsx": $25,
    "./routes/oauth2/google/index.tsx": $26,
    "./routes/oauth2/login.tsx": $27,
    "./routes/signup.tsx": $28,
  },
  islands: {
    "./islands/AccountForm.tsx": $$0,
    "./islands/AppDataEditor.tsx": $$1,
    "./islands/Banner.tsx": $$2,
    "./islands/CopyButton.tsx": $$3,
    "./islands/CopyText.tsx": $$4,
    "./islands/Counter.tsx": $$5,
    "./islands/Input.tsx": $$6,
    "./islands/Login.tsx": $$7,
    "./islands/PersonalForm.tsx": $$8,
    "./islands/ProfileNavButton.tsx": $$9,
    "./islands/SearchButton.tsx": $$10,
    "./islands/UserNavbar.tsx": $$11,
  },
  baseUrl: import.meta.url,
};

export default manifest;
