// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account_middleware from "./routes/account/_middleware.ts";
import * as $account_create_page_ from "./routes/account/create/[page].tsx";
import * as $account_create_index from "./routes/account/create/index.tsx";
import * as $api_me from "./routes/api/me.tsx";
import * as $api_oauth_token from "./routes/api/oauth/token.tsx";
import * as $dev_dashboard_middleware from "./routes/dev/dashboard/_middleware.ts";
import * as $dev_dashboard_app_id_slug_create from "./routes/dev/dashboard/app/[id]/[[slug]]/create.tsx";
import * as $dev_dashboard_app_id_slug_index from "./routes/dev/dashboard/app/[id]/[[slug]]/index.tsx";
import * as $dev_dashboard_create_app from "./routes/dev/dashboard/create-app.tsx";
import * as $dev_dashboard_index from "./routes/dev/dashboard/index.tsx";
import * as $dev_index from "./routes/dev/index.tsx";
import * as $dev_login from "./routes/dev/login.tsx";
import * as $docs_slug_ from "./routes/docs/[...slug].tsx";
import * as $docs_out from "./routes/docs/out.tsx";
import * as $friends_index from "./routes/friends/index.tsx";
import * as $friends_requests from "./routes/friends/requests.tsx";
import * as $friends_search from "./routes/friends/search.tsx";
import * as $home from "./routes/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $oauth2_auth from "./routes/oauth2/auth.tsx";
import * as $oauth2_dev_fync_callback from "./routes/oauth2/dev/fync/callback.tsx";
import * as $oauth2_dev_fync_index from "./routes/oauth2/dev/fync/index.tsx";
import * as $oauth2_discord_callback from "./routes/oauth2/discord/callback.tsx";
import * as $oauth2_discord_df_cid_cb from "./routes/oauth2/discord/df/[cid]/cb.tsx";
import * as $oauth2_discord_index from "./routes/oauth2/discord/index.tsx";
import * as $oauth2_forgot_password from "./routes/oauth2/forgot-password.tsx";
import * as $oauth2_google_callback from "./routes/oauth2/google/callback.tsx";
import * as $oauth2_google_index from "./routes/oauth2/google/index.tsx";
import * as $oauth2_login from "./routes/oauth2/login.tsx";
import * as $partials_dev_dashboard_app_id_slug_index from "./routes/partials/dev/dashboard/app/[id]/[[slug]]/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $users_id_accept_friend from "./routes/users/[id]/accept-friend.tsx";
import * as $users_id_add_friend from "./routes/users/[id]/add-friend.tsx";
import * as $users_id_cancel from "./routes/users/[id]/cancel.tsx";
import * as $users_id_edit from "./routes/users/[id]/edit.tsx";
import * as $users_id_index from "./routes/users/[id]/index.tsx";
import * as $users_id_reject from "./routes/users/[id]/reject.tsx";
import * as $AccountForm from "./islands/AccountForm.tsx";
import * as $AppDataEditor from "./islands/AppDataEditor.tsx";
import * as $ArrayInput from "./islands/ArrayInput.tsx";
import * as $AuthUrlGenerator from "./islands/AuthUrlGenerator.tsx";
import * as $Banner from "./islands/Banner.tsx";
import * as $CopyButton from "./islands/CopyButton.tsx";
import * as $CopyText from "./islands/CopyText.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DataInput from "./islands/DataInput.tsx";
import * as $DiscordAuthEditor from "./islands/DiscordAuthEditor.tsx";
import * as $FriendingButton from "./islands/FriendingButton.tsx";
import * as $Input from "./islands/Input.tsx";
import * as $InteractionEditor from "./islands/InteractionEditor.tsx";
import * as $InteractionsEditor from "./islands/InteractionsEditor.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $PersonalForm from "./islands/PersonalForm.tsx";
import * as $ProfileNavButton from "./islands/ProfileNavButton.tsx";
import * as $ScopePicker from "./islands/ScopePicker.tsx";
import * as $SearchButton from "./islands/SearchButton.tsx";
import * as $Select from "./islands/Select.tsx";
import * as $UserNavbar from "./islands/UserNavbar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account/_middleware.ts": $account_middleware,
    "./routes/account/create/[page].tsx": $account_create_page_,
    "./routes/account/create/index.tsx": $account_create_index,
    "./routes/api/me.tsx": $api_me,
    "./routes/api/oauth/token.tsx": $api_oauth_token,
    "./routes/dev/dashboard/_middleware.ts": $dev_dashboard_middleware,
    "./routes/dev/dashboard/app/[id]/[[slug]]/create.tsx":
      $dev_dashboard_app_id_slug_create,
    "./routes/dev/dashboard/app/[id]/[[slug]]/index.tsx":
      $dev_dashboard_app_id_slug_index,
    "./routes/dev/dashboard/create-app.tsx": $dev_dashboard_create_app,
    "./routes/dev/dashboard/index.tsx": $dev_dashboard_index,
    "./routes/dev/index.tsx": $dev_index,
    "./routes/dev/login.tsx": $dev_login,
    "./routes/docs/[...slug].tsx": $docs_slug_,
    "./routes/docs/out.tsx": $docs_out,
    "./routes/friends/index.tsx": $friends_index,
    "./routes/friends/requests.tsx": $friends_requests,
    "./routes/friends/search.tsx": $friends_search,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/oauth2/auth.tsx": $oauth2_auth,
    "./routes/oauth2/dev/fync/callback.tsx": $oauth2_dev_fync_callback,
    "./routes/oauth2/dev/fync/index.tsx": $oauth2_dev_fync_index,
    "./routes/oauth2/discord/callback.tsx": $oauth2_discord_callback,
    "./routes/oauth2/discord/df/[cid]/cb.tsx": $oauth2_discord_df_cid_cb,
    "./routes/oauth2/discord/index.tsx": $oauth2_discord_index,
    "./routes/oauth2/forgot-password.tsx": $oauth2_forgot_password,
    "./routes/oauth2/google/callback.tsx": $oauth2_google_callback,
    "./routes/oauth2/google/index.tsx": $oauth2_google_index,
    "./routes/oauth2/login.tsx": $oauth2_login,
    "./routes/partials/dev/dashboard/app/[id]/[[slug]]/index.tsx":
      $partials_dev_dashboard_app_id_slug_index,
    "./routes/search.tsx": $search,
    "./routes/signup.tsx": $signup,
    "./routes/users/[id]/accept-friend.tsx": $users_id_accept_friend,
    "./routes/users/[id]/add-friend.tsx": $users_id_add_friend,
    "./routes/users/[id]/cancel.tsx": $users_id_cancel,
    "./routes/users/[id]/edit.tsx": $users_id_edit,
    "./routes/users/[id]/index.tsx": $users_id_index,
    "./routes/users/[id]/reject.tsx": $users_id_reject,
  },
  islands: {
    "./islands/AccountForm.tsx": $AccountForm,
    "./islands/AppDataEditor.tsx": $AppDataEditor,
    "./islands/ArrayInput.tsx": $ArrayInput,
    "./islands/AuthUrlGenerator.tsx": $AuthUrlGenerator,
    "./islands/Banner.tsx": $Banner,
    "./islands/CopyButton.tsx": $CopyButton,
    "./islands/CopyText.tsx": $CopyText,
    "./islands/Counter.tsx": $Counter,
    "./islands/DataInput.tsx": $DataInput,
    "./islands/DiscordAuthEditor.tsx": $DiscordAuthEditor,
    "./islands/FriendingButton.tsx": $FriendingButton,
    "./islands/Input.tsx": $Input,
    "./islands/InteractionEditor.tsx": $InteractionEditor,
    "./islands/InteractionsEditor.tsx": $InteractionsEditor,
    "./islands/Login.tsx": $Login,
    "./islands/PersonalForm.tsx": $PersonalForm,
    "./islands/ProfileNavButton.tsx": $ProfileNavButton,
    "./islands/ScopePicker.tsx": $ScopePicker,
    "./islands/SearchButton.tsx": $SearchButton,
    "./islands/Select.tsx": $Select,
    "./islands/UserNavbar.tsx": $UserNavbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
