// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/account/create.tsx";
import * as $4 from "./routes/dev/index.tsx";
import * as $5 from "./routes/dev/sign-in.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/login.tsx";
import * as $8 from "./routes/oauth2/auth.tsx";
import * as $9 from "./routes/oauth2/google/callback.tsx";
import * as $10 from "./routes/oauth2/google/index.tsx";
import * as $11 from "./routes/signup.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Input.tsx";
import * as $$2 from "./islands/Login.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/account/create.tsx": $3,
    "./routes/dev/index.tsx": $4,
    "./routes/dev/sign-in.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/login.tsx": $7,
    "./routes/oauth2/auth.tsx": $8,
    "./routes/oauth2/google/callback.tsx": $9,
    "./routes/oauth2/google/index.tsx": $10,
    "./routes/signup.tsx": $11,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Input.tsx": $$1,
    "./islands/Login.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
